url: https://udework.com
#baseurl: /agency-jekyll-theme/

# Site settings
title: UDE Work
email: hi@udework.com
description: "武汉优帝易科技有限公司是一家电子、IT解决方案提供商，旨在为客户提供高效快速低成本的模块化部件及解决方案。"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 3cc
  secondary: 036  
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: weibo
    url: http://weibo.com/udework
  - title: weixin
    url:
  - title: envelope
    url: mailto:hi@udework.com
  - title: github
    url: http://github.com/udework

# Postal address (add as many lines as necessary)
address:
  - line: 湖北省武汉市东湖高新区
  - line: 高新二路41号谷方3栋2层C3-2室

contact:
  address: 湖北省武汉市东湖高新区高新二路41号谷方3栋2层C3-2室
  e-mail: hi@udework.com
  phone: +86-27-51239984

# Build settings
markdown: kramdown
permalink: pretty